/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './core/routes/__root'
import { Route as LoginImport } from './core/routes/login'
import { Route as ResetPasswordRouteImport } from './core/routes/reset-password/route'
import { Route as RegisterRouteImport } from './core/routes/register/route'
import { Route as AuthRouteImport } from './core/routes/_auth/route'
import { Route as IndexImport } from './core/routes/index'
import { Route as ResetPasswordVerifyImport } from './core/routes/reset-password/verify'
import { Route as ResetPasswordSetImport } from './core/routes/reset-password/set'
import { Route as ResetPasswordInitImport } from './core/routes/reset-password/init'
import { Route as RegisterVerifyImport } from './core/routes/register/verify'
import { Route as RegisterInitImport } from './core/routes/register/init'
import { Route as AuthSubsListImport } from './core/routes/_auth/subs-list'
import { Route as AuthSettingsImport } from './core/routes/_auth/settings'
import { Route as AuthProfileImport } from './core/routes/_auth/profile'
import { Route as AuthLogoutImport } from './core/routes/_auth/logout'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRouteRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRouteRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordVerifyRoute = ResetPasswordVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)

const ResetPasswordSetRoute = ResetPasswordSetImport.update({
  id: '/set',
  path: '/set',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)

const ResetPasswordInitRoute = ResetPasswordInitImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)

const RegisterVerifyRoute = RegisterVerifyImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => RegisterRouteRoute,
} as any)

const RegisterInitRoute = RegisterInitImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => RegisterRouteRoute,
} as any)

const AuthSubsListRoute = AuthSubsListImport.update({
  id: '/subs-list',
  path: '/subs-list',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/subs-list': {
      id: '/_auth/subs-list'
      path: '/subs-list'
      fullPath: '/subs-list'
      preLoaderRoute: typeof AuthSubsListImport
      parentRoute: typeof AuthRouteImport
    }
    '/register/init': {
      id: '/register/init'
      path: '/init'
      fullPath: '/register/init'
      preLoaderRoute: typeof RegisterInitImport
      parentRoute: typeof RegisterRouteImport
    }
    '/register/verify': {
      id: '/register/verify'
      path: '/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof RegisterVerifyImport
      parentRoute: typeof RegisterRouteImport
    }
    '/reset-password/init': {
      id: '/reset-password/init'
      path: '/init'
      fullPath: '/reset-password/init'
      preLoaderRoute: typeof ResetPasswordInitImport
      parentRoute: typeof ResetPasswordRouteImport
    }
    '/reset-password/set': {
      id: '/reset-password/set'
      path: '/set'
      fullPath: '/reset-password/set'
      preLoaderRoute: typeof ResetPasswordSetImport
      parentRoute: typeof ResetPasswordRouteImport
    }
    '/reset-password/verify': {
      id: '/reset-password/verify'
      path: '/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof ResetPasswordVerifyImport
      parentRoute: typeof ResetPasswordRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSubsListRoute: typeof AuthSubsListRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLogoutRoute: AuthLogoutRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSubsListRoute: AuthSubsListRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface RegisterRouteRouteChildren {
  RegisterInitRoute: typeof RegisterInitRoute
  RegisterVerifyRoute: typeof RegisterVerifyRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterInitRoute: RegisterInitRoute,
  RegisterVerifyRoute: RegisterVerifyRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface ResetPasswordRouteRouteChildren {
  ResetPasswordInitRoute: typeof ResetPasswordInitRoute
  ResetPasswordSetRoute: typeof ResetPasswordSetRoute
  ResetPasswordVerifyRoute: typeof ResetPasswordVerifyRoute
}

const ResetPasswordRouteRouteChildren: ResetPasswordRouteRouteChildren = {
  ResetPasswordInitRoute: ResetPasswordInitRoute,
  ResetPasswordSetRoute: ResetPasswordSetRoute,
  ResetPasswordVerifyRoute: ResetPasswordVerifyRoute,
}

const ResetPasswordRouteRouteWithChildren =
  ResetPasswordRouteRoute._addFileChildren(ResetPasswordRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof AuthLogoutRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/subs-list': typeof AuthSubsListRoute
  '/register/init': typeof RegisterInitRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/reset-password/init': typeof ResetPasswordInitRoute
  '/reset-password/set': typeof ResetPasswordSetRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof AuthLogoutRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/subs-list': typeof AuthSubsListRoute
  '/register/init': typeof RegisterInitRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/reset-password/init': typeof ResetPasswordInitRoute
  '/reset-password/set': typeof ResetPasswordSetRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/register': typeof RegisterRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/subs-list': typeof AuthSubsListRoute
  '/register/init': typeof RegisterInitRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/reset-password/init': typeof ResetPasswordInitRoute
  '/reset-password/set': typeof ResetPasswordSetRoute
  '/reset-password/verify': typeof ResetPasswordVerifyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/register'
    | '/reset-password'
    | '/login'
    | '/logout'
    | '/profile'
    | '/settings'
    | '/subs-list'
    | '/register/init'
    | '/register/verify'
    | '/reset-password/init'
    | '/reset-password/set'
    | '/reset-password/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/register'
    | '/reset-password'
    | '/login'
    | '/logout'
    | '/profile'
    | '/settings'
    | '/subs-list'
    | '/register/init'
    | '/register/verify'
    | '/reset-password/init'
    | '/reset-password/set'
    | '/reset-password/verify'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/register'
    | '/reset-password'
    | '/login'
    | '/_auth/logout'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/subs-list'
    | '/register/init'
    | '/register/verify'
    | '/reset-password/init'
    | '/reset-password/set'
    | '/reset-password/verify'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  ResetPasswordRouteRoute: ResetPasswordRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/register",
        "/reset-password",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/logout",
        "/_auth/profile",
        "/_auth/settings",
        "/_auth/subs-list"
      ]
    },
    "/register": {
      "filePath": "register/route.tsx",
      "children": [
        "/register/init",
        "/register/verify"
      ]
    },
    "/reset-password": {
      "filePath": "reset-password/route.tsx",
      "children": [
        "/reset-password/init",
        "/reset-password/set",
        "/reset-password/verify"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/logout": {
      "filePath": "_auth/logout.tsx",
      "parent": "/_auth"
    },
    "/_auth/profile": {
      "filePath": "_auth/profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_auth/subs-list": {
      "filePath": "_auth/subs-list.tsx",
      "parent": "/_auth"
    },
    "/register/init": {
      "filePath": "register/init.tsx",
      "parent": "/register"
    },
    "/register/verify": {
      "filePath": "register/verify.tsx",
      "parent": "/register"
    },
    "/reset-password/init": {
      "filePath": "reset-password/init.tsx",
      "parent": "/reset-password"
    },
    "/reset-password/set": {
      "filePath": "reset-password/set.tsx",
      "parent": "/reset-password"
    },
    "/reset-password/verify": {
      "filePath": "reset-password/verify.tsx",
      "parent": "/reset-password"
    }
  }
}
ROUTE_MANIFEST_END */
